server:
  port: 9002
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kita_db
    username: test
    password: pasw0rd
  jpa:
    properties:
      hibernate:
        naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: create
    show_sql: true
kafka:
  consumer:
    bootstrap-servers: localhost:9092
    group-id: price_service
    auto-offset-reset: earliest
  producer:
    bootstrap-servers: localhost:9092
topic.output:
  kita-place: kita.place
topic.input:
  reserve-place: reserve.place
  claim-place: claim.place
test-mode:
  active: true
  period: 5